import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styled from "styled-components";
import CardGrid from "../components/CardGrid";
import { Container, H2 } from "../components/Layout";
import { Colab } from "../interface";
import { client } from "../libs/client";
import { HeaderMenu } from "components/HomeHeader";

const Top = styled.div`
  padding: 180px 0 100px 0;
  height: 400px;
  position: relative;
  text-align: center;

  > h1 {
    font-size: 5em;
    opacity: 0.7;
    letter-spacing: 5px;
    text-align: center;
    color: white;
  }
`;

function Home(allColab: { allColab: Colab[] }) {
  // createdAtで並び替えて、先頭のみnew_colabとする
  const new_colab: Colab = allColab.allColab.sort((a, b) => {
    if (a.createdAt < b.createdAt) {
      return 1;
    }
    if (a.createdAt > b.createdAt) {
      return -1;
    }
    return 0;
  })[0];
  return (
    <>
      <Head>
        <title>Colab Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top>
        <Image
          alt="Picture of starry sky"
          src="/starry_sky.jpg"
          layout="fill"
        />
        <HeaderMenu />
        <h1>Let&apos;s Enjoy Computer Science !</h1>
      </Top>

      <Container>
        <H2>気になるテーマからはじめてみよう！</H2>
        <p>
          Google Colaboratoryを使ってPythonの練習をしましょう！
          <br />
          <br />
          Pythonを習ったばかりで、お手軽な問題に挑戦したい方。
          <br />
          学校の授業でPythonの演習をしたい先生。
          <br />
          <br />
          お好きな問題をぜひ自分のGoogle Colaboratoryで動かしてみましょう！
        </p>
        <H2>最新のテーマ</H2>
        <CardGrid items={[new_colab]} />
      </Container>

      {/* <Footer>
      <p>Let&apos;s Enjoy Programming !!</p>
    </Footer> */}
    </>
  );
}

// データをテンプレートに受け渡す部分の処理を記述
export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({ endpoint: "colab-url" });
  const allColab = data.contents;

  return {
    props: {
      allColab,
    },
  };
};

export default Home;
