import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import { Container, Footer, Main } from '../components/Layout'
import styled from 'styled-components'
import { client } from "../libs/client";


const Title = styled.h1`
  font-size: 5.0em;
  text-align: center;
  color: palevioletred;

  >span{
    color: red;
  }
`;

const Card = styled.a`
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  width: 45%;
  height: 80px;

  &:hover{
    color: #0070f3;
    border-color: #0070f3;
  }

  >h2{
    margin: 0 0 1rem 0;
    font-size: 2.0rem;
  }

  >p{
    margin: 0;
    font-size: 1.3rem;
    line-height: 1.5;
  }
`;

const Grid = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 800px;
  margin: 10px auto;

  @media (max-width: 600px) {
    width: 100%;
    flex-direction: column;
  }
`;

type Colab = {
  id?: string,
  createdAt: string,
  updatedAt?: string,
  publishedAt?: string,
  revisedAt?: string,
  name: string,
  url: string,
  skill: string[],
  editor?: string
  youtubeURL?: string 
}



const Home: NextPage = ({colab}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Container>
      <Head>
        <title>Enjoy Computer Science</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Let&apos;s Enjoy Computer Science !
        </Title>

        <Grid>
          {colab.map((colab: Colab) => (
              <Card
              href={colab.url} key={colab.id}
            >
              <h2>{colab.name}</h2>
            </Card>
          ))}
        </Grid>
        {/* 
        next.js ページへのリンク
        <Link href={`/blog/${colab.id}`}>
                    <a>{colab.name}</a>
                  </Link><Link href={`/blog/${colab.id}`}>
                    <a>{colab.name}</a>
                  </Link>
        */}
      </Main>

      <Footer>
        <p>Let&apos;s Enjoy Programming !!</p>
      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      </Footer>
    </Container>
  )
}


// データをテンプレートに受け渡す部分の処理を記述
export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({ endpoint: "colab-url" });

  return {
    props: {
      colab: data.contents,
    },
  };
};



export default Home